spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/Users
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
security.jwt.secret=change-this-secret-key-to-a-secure-256-bit-value
security.jwt.expiration-seconds=3600
